name: Lint
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.18.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: download dependencies
        run: go mod vendor
      - name: Lint
        run: |
          make install-linter
          make lint